blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('generate/', views.generate_pairs, name='generate_pairs'),
    path('show/', views.show_pair, name='show_pair'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/models.py
from django.db import models


class Present(models.Model):
    name = models.CharField(max_length=50)
    code = models.CharField(max_length=50)
    name_of_friend = models.CharField(max_length=50, blank=True)

blog/views.py
import random

from django.shortcuts import render
from .models import Present


def index(request):
    friend_list = Present.objects.all()
    return render(request, 'blog/index.html', {'friend_list': friend_list})


def show_pair(request):
    code = request.POST['code']
    friend = Present.objects.get(code=code)
    return render(request, 'blog/show_pair.html', {'friend': friend})


def check(friend_list):
    for friend in friend_list:
        if friend.name == friend.name_of_friend:
            return False
    return True


def random_shuffle(friend_list):
    for x in range(5):
        first = random.randrange(friend_list.count())
        second = random.randrange(friend_list.count())
        friend_list[first].name_of_friend, friend_list[second].name_of_friend = \
            friend_list[second].name_of_friend, friend_list[first].name_of_friend

    for friend in friend_list:
        friend.save()
    return friend_list


def generate_pairs(request):
    friend_list = Present.objects.all()
    for x in range(5):
        friend_list = random_shuffle(friend_list)
    while not check(friend_list):
        friend_list = random_shuffle(friend_list)
    return render(request, 'blog/index.html', {'friend_list': friend_list})

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="ru">

{% load static %}

<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<meta name="viewport" content="width=device-width, initial-scale=1">

<style>
    body, html {
        background-image: url("{% static "images/background.jpg" %}");
        background-size: auto;
        height: 100%;
        margin: 0;
}
</style>
<body>
    <meta charset="UTF-8">
    <title>Santa 2020</title>
    {% block content %}
    {% endblock %}
</body>

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% load static %}
{% block content %}
    <div class="w3-xxxlarge w3-center" >Санта 2020</div>
    <div class="w3-content">
    <div class="w3-row-padding">
        <div class="w3-half">
            <img src="{% static "images/santa.png" %}" style="width: 90%" alt="santa">
        </div>
        <div class="w3-half">
        <h2><b>Учасники:</b></h2>
            {% for friend in friend_list %}
                <p><b>{{ friend.name }}</b></p>
            {% endfor %}
        </div>
    </div>
    <form class="w3-padding" action="{% url 'blog:show_pair'%}" method="post">
      {% csrf_token %}
      <label for="code" class="w3-xlarge"><b style="opacity:1">Узнать, кому я дарю подарок:</b></label>
      <input class="w3-input" type="text" id="code"  name="code" placeholder="Введи код.." required>
      <button class="w3-red w3-margin-top w3-button w3-round-large" type="submit">Узнать</button>
    </form>
    {% if user.is_authenticated %}
        <br>
        <br>
        <br>
        <br>
        <br>
    <a href="{% url 'blog:generate_pairs'%}" class="w3-button">Generate random pairs</a>
    {% endif %}
    </div>
{% endblock %}

blog/templates/blog/show_pair.html
{% extends 'blog/base.html' %}

{% load static %}
{% block content %}
    <div class="w3-content">
        <div class="w3-center">
            <p class="w3-large">Ты Санта для:</p>
            <p class="w3-xxlarge">{{ friend.name_of_friend }}</p>

        </div>
        <p class="w3-padding-large w3-xlarge">Правила:</p>
        <ul class="w3-large">
            <li>Подарок от 100 до 200 грн</li>
            <li>Подарок обязательно подписать (желательно вложить внутырь)</li>
            <li>Сложить подарки вместе возле ёлки</li>
        </ul>
        <div class="w3-center">
            <img src="{% static "images/chill_santa.jpg" %}" style="width: 60%" alt="">
        </div>
    </div>

{% endblock %}